# Visit https://fossa.com to learn more

version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:stumble/v8go.git
analyze:
  modules:
    - name: v8go
      type: go
      target: github.com/stumble/v8go
      path: .
