name: Sync Submodule Dependencies

on:
  push:
    branches:
    - master
    paths:
    - "deps/*_*/**"
  workflow_dispatch:
  workflow_call:
    inputs:
      sha:
        description: "The commit to check out at. Defaults to the parent workflow's github.sha."
        required: false
        type: string
    outputs:
      sha:
        description: The resulting SHA commitish.
        value: ${{ jobs.sync.outputs.sha }}

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    outputs:
      committed: ${{ steps.commit.outputs.committed }}
      sha: ${{ steps.commit.outputs.commit_long_sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Our git log in deps/ requires an arbitrarily deep history.
        fetch-depth: 0
        ref: ${{ inputs.sha }}

    - id: info
      name: Extract Information
      run: |
        set -o pipefail
        submods=( $(ls deps/*_*/cgo.go | xargs -r dirname) )

        # This is the latest commit affecting any file in the submodules.
        # Thus, this workflow is idempotent.
        sha="$(git log -n 1 --pretty=format:%H -- "${submods[@]}")"

        echo "submodules=${submods[*]}" >>"$GITHUB_OUTPUT"
        echo "sha=$sha" >>"$GITHUB_OUTPUT"
        echo "short-sha=${sha::8}" >>"$GITHUB_OUTPUT"

    - name: Set Up Workspace
      # Submodules shouldn't cause a download.
      # TODO: figure out why this isn't enough.
      run: |
        submods=( ${{ steps.info.outputs.submodules }} )
        go work init . "${submods[@]}"

    - name: Update go.mod
      run: |
        sha="${{ steps.info.outputs.sha }}"
        submods=( $(for submod in ${{ steps.info.outputs.submodules }}; do echo "github.com/${{ github.repository }}/$submod@$sha" ; done) )
        go get "${submods[@]}"

    - id: commit
      name: Commit
      uses: EndBug/add-and-commit@v9
      with:
          add: |
              go.mod
              go.sum
          fetch: false
          message: |
            Bump go.mod to latest submodules (${{ steps.info.outputs.short-sha }})

            Auto-generated pull request from workflows/syncsubdeps.

    - name: Create Summary
      run: |
          echo "Commit: https://github.com/tommie/v8go/commit/${{ steps.commit.outputs.commit_long_sha }}" >>"$GITHUB_STEP_SUMMARY"
