name: V8 Upgrade

on:
    workflow_dispatch:
    schedule:
    - cron: '0 0 * * *' # Run every day

jobs:
    upgrade:
        name: Upgrade V8
        runs-on: ubuntu-latest
        outputs:
          committed: ${{ steps.commit.outputs.committed }}
          sha: ${{ steps.commit.outputs.commit_long_sha }}
          has_upgrade: ${{ steps.check_v8.outputs.has_upgrade }}
          latest_v8_hash: ${{ steps.check_v8.outputs.latest_v8_hash }}
        steps:
        - name: Install Utilities
          run: |
              sudo apt-get update
              sudo apt-get install -qy --no-install-recommends jq

        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 1

        - id: check_v8
          name: Check Latest Stable Chromium V8
          run: |
              set -o pipefail
              wget -q -O- "https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1&offset=0" | jq -r ".[0].hashes.v8" >deps/latest_v8_hash
              echo "latest_v8_hash=$(<deps/latest_v8_hash)" >>"$GITHUB_OUTPUT"
              echo "has_upgrade=$(git status --porcelain | grep -q . && echo true || echo false)" >>"$GITHUB_OUTPUT"
              git status --porcelain
              cat "$GITHUB_OUTPUT"

        - id: commit
          name: Commit
          if: ${{ steps.check_v8.outputs.has_upgrade == 'true' }}
          uses: EndBug/add-and-commit@v9
          with:
              add: deps/latest_v8_hash
              fetch: false
              message: |
                  Records new V8 release: ${{ steps.check_v8.outputs.latest_v8_hash }}
                  
                  This is an automated bump of the V8 release hash based on the Chromium dashboard.
                  Code changes will happen on the next run of the build workflow.

        - name: Create Summary
          if: ${{ steps.commit.outputs.committed == 'true' }}
          run: |
              echo "Commit: https://github.com/tommie/v8go/commit/${{ steps.commit.outputs.commit_long_sha }}" >>"$GITHUB_STEP_SUMMARY"

        - name: Create Summary (no upgrade)
          if: ${{ steps.commit.outputs.committed != 'true' }}
          run: |
              echo "No V8 upgrade available." >>"$GITHUB_STEP_SUMMARY"

    build:
        name: Run V8 Build
        needs: upgrade
        if: ${{ needs.upgrade.outputs.committed == 'true' }}
        uses: ./.github/workflows/v8build.yml
        with:
            sha: ${{ needs.upgrade.outputs.sha }}
