name: V8 Upgrade

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # Run every day

jobs:
  upgrade:
    name: Upgrade V8
    runs-on: ubuntu-latest
    outputs:
      has_upgrade: ${{ steps.check_v8.outputs.has_upgrade }}
      latest_v8_hash: ${{ steps.check_v8.outputs.latest_v8_hash }}
    steps:
    - name: Install Utilities
      run: |
        sudo apt-get update
        sudo apt-get install -qy --no-install-recommends jq

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - id: check_v8
      name: Check Latest Stable Chromium V8
      run: |
        set -o pipefail
        wget -q -O- "https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1&offset=0" | jq -r ".[0].hashes.v8" >deps/v8_hash
        echo "latest_v8_hash=$(<deps/v8_hash)" >>"$GITHUB_OUTPUT"
        echo "has_upgrade=$(git status --porcelain | grep -q . && echo true || echo false)" >>"$GITHUB_OUTPUT"

    - name: Create Summary
      if: ${{ steps.check_v8.outputs.has_upgrade == 'true' }}
      run: |
        echo "New V8 hash: ${{ steps.check_v8.outputs.latest_v8_hash }}" >>"$GITHUB_STEP_SUMMARY"

    - name: Create Summary (no upgrade)
      if: ${{ steps.check_v8.outputs.has_upgrade != 'true' }}
      run: |
        echo "No V8 upgrade available." >>"$GITHUB_STEP_SUMMARY"

  build:
    name: Run V8 Build
    needs: upgrade
    if: ${{ needs.upgrade.outputs.has_upgrade == 'true' }}
    uses: ./.github/workflows/v8build.yml
    with:
      v8_hash: ${{ needs.upgrade.outputs.latest_v8_hash }}

  release:
    name: Make A Release
    needs: build
    if: ${{ needs.build.outputs.committed == 'true' && github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/release.yml
    with:
      draft: false
      version: '+0.1.0'
      sha: ${{ needs.build.outputs.sha }}
